// scripts/write-config.js
// Run during build on Vercel/Netlify or locally to generate frontend/config.js from env vars.
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'frontend', 'config.js');
const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error('Missing SUPABASE_URL or SUPABASE_ANON_KEY environment variables.');
  process.exit(1);
}

const content = `// Auto-generated by scripts/write-config.js\nconst SUPABASE_URL = '${url}';\nconst SUPABASE_ANON_KEY = '${key}';\n`;
fs.writeFileSync(outPath, content, { encoding: 'utf8' });
console.log('Wrote', outPath);
